### ISSUE TITLE
exit 3 on unrecognized projection

### ISSUE THREAD

**Issue by isiyu** [mapbox/preprocessorcerer#48]
Got an unpacker error of a job retrying because of an unrecognized projection. The job was ending with exit code 8. Per chat with @rclark `preprocessorcerer` should identify these cases and `exit 3`, along with an appropriate error message

cc @GretaCB

`s3://mapbox/tmp/isiyu/dimentians_unrecognizedProjection.tif`
upload id: `cigl1ze2y008yt7m3ohbd45k7`
jobid: `8456748d-c9a1-447e-8256-da14b5e3acc0`

Job error:
```
[Wed, 04 Nov 2015 17:05:39 GMT] [info] [8456748d-c9a1-447e-8256-da14b5e3acc0] [watchbot] Returned message to SQS with 128s timeout
[Wed, 04 Nov 2015 17:07:47 GMT] [info] [8456748d-c9a1-447e-8256-da14b5e3acc0] [watchbot] Received message: 8456748d-c9a1-447e-8256-da14b5e3acc0
[Wed, 04 Nov 2015 17:07:47 GMT] [info] [8456748d-c9a1-447e-8256-da14b5e3acc0] [watchbot] ReceiptHandle: AQEBhoPP6vMtKjYshhjmjewN/qUHX9HGKGSIHpDPbD12O9Wx1WRsEMWtKYzO4n5QWXKSGkJyWFFWWkGIc6IXReLwr4gBuqLYJkRfUHGObYHNLg9p/Lfq1WUF+qX3nMb4tkMHkwY2rVHOudWG6+lDAz+26nN4dGKdqKVCfIm9IGJYKeR5BG0XEMbs38OOxjqSPWCH69NGaXX/jYCFpdy8VAN/4a2jN+3vzzzpKG1w5lPCFcaDU2cf9XzkMaH3aOdIkB58s1CK94GHOXQeNXxeF8F3e59fdnO4ECDVtc+CLThlXL1CPILTB762RVb26Kj/KRRJue35c47mvLO0zGSwX2SUVOdAlmwUIlRDrqe7wUsTnB69YzyksY4Bf6QvmbHua3Wa
[Wed, 04 Nov 2015 17:07:47 GMT] [info] [8456748d-c9a1-447e-8256-da14b5e3acc0] [watchbot] SentTimestamp: 1446656592265
[Wed, 04 Nov 2015 17:07:47 GMT] [info] [8456748d-c9a1-447e-8256-da14b5e3acc0] [watchbot] ApproximateFirstReceiveTimestamp: 1446656592265
[Wed, 04 Nov 2015 17:07:47 GMT] [info] [8456748d-c9a1-447e-8256-da14b5e3acc0] [watchbot] ApproximateReceiveCount: 8
[Wed, 04 Nov 2015 17:07:47 GMT] [info] [8456748d-c9a1-447e-8256-da14b5e3acc0] [watchbot] Subject: map.upload.created
[Wed, 04 Nov 2015 17:07:47 GMT] [info] [8456748d-c9a1-447e-8256-da14b5e3acc0] [watchbot] Message: {"id":"cigl1ze2y008yt7m3ohbd45k7","owner":"dimentians","data":"dimentians.xcuzbyb9","url":"http://tilestream-tilesets-production.s3.amazonaws.com/e7/_pending/maayp2ig3metv900m4oy1lgic/dimentians","name":null,"patch":false}
[Wed, 04 Nov 2015 17:07:48 GMT] [info] [8456748d-c9a1-447e-8256-da14b5e3acc0] [cigl1ze2y008yt7m3ohbd45k7] Checked if upload has already errored: false
[Wed, 04 Nov 2015 17:07:50 GMT] [info] [8456748d-c9a1-447e-8256-da14b5e3acc0] [cigl1ze2y008yt7m3ohbd45k7] Downloaded file from http://tilestream-tilesets-production.s3.amazonaws.com/e7/_pending/maayp2ig3metv900m4oy1lgic/dimentians to /tmp/unpacker.OAQYBwt5/original
[Wed, 04 Nov 2015 17:07:50 GMT] [info] [8456748d-c9a1-447e-8256-da14b5e3acc0] [cigl1ze2y008yt7m3ohbd45k7] File type detected: tif
[Wed, 04 Nov 2015 17:07:50 GMT] [error] [8456748d-c9a1-447e-8256-da14b5e3acc0] [cigl1ze2y008yt7m3ohbd45k7] ERROR 6: Mercator_1SP with scale != 1.0 and latitude of origin != 0, not supported by PROJ.4.
[Wed, 04 Nov 2015 17:07:50 GMT] [error] [8456748d-c9a1-447e-8256-da14b5e3acc0] ERROR 6: Mercator_1SP with scale != 1.0 and latitude of origin != 0, not supported by PROJ.4.
[Wed, 04 Nov 2015 17:07:50 GMT] [error] [8456748d-c9a1-447e-8256-da14b5e3acc0] /usr/local/src/service-worker/node_modules/tilelive-omnivore/node_modules/mapnik-omnivore/lib/raster.js:89
[Wed, 04 Nov 2015 17:07:50 GMT] [error] [8456748d-c9a1-447e-8256-da14b5e3acc0]   var current = new mapnik.Projection(this.projection);
[Wed, 04 Nov 2015 17:07:50 GMT] [error] [8456748d-c9a1-447e-8256-da14b5e3acc0]                 ^
[Wed, 04 Nov 2015 17:07:50 GMT] [error] [8456748d-c9a1-447e-8256-da14b5e3acc0] TypeError: please provide a proj4 intialization string
[Wed, 04 Nov 2015 17:07:50 GMT] [error] [8456748d-c9a1-447e-8256-da14b5e3acc0]     at Raster.getExtent (/usr/local/src/service-worker/node_modules/tilelive-omnivore/node_modules/mapnik-omnivore/lib/raster.js:89:17)
[Wed, 04 Nov 2015 17:07:50 GMT] [error] [8456748d-c9a1-447e-8256-da14b5e3acc0]     at Raster.getCenter (/usr/local/src/service-worker/node_modules/tilelive-omnivore/node_modules/mapnik-omnivore/lib/raster.js:78:8)
[Wed, 04 Nov 2015 17:07:50 GMT] [error] [8456748d-c9a1-447e-8256-da14b5e3acc0]     at /usr/local/src/service-worker/node_modules/tilelive-omnivore/node_modules/mapnik-omnivore/index.js:87:12
[Wed, 04 Nov 2015 17:07:50 GMT] [error] [8456748d-c9a1-447e-8256-da14b5e3acc0]     at pop (/usr/local/src/service-worker/node_modules/queue-async/queue.js:24:14)
[Wed, 04 Nov 2015 17:07:50 GMT] [error] [8456748d-c9a1-447e-8256-da14b5e3acc0]     at /usr/local/src/service-worker/node_modules/queue-async/queue.js:38:39
[Wed, 04 Nov 2015 17:07:50 GMT] [error] [8456748d-c9a1-447e-8256-da14b5e3acc0]     at /usr/local/src/service-worker/node_modules/tilelive-omnivore/node_modules/mapnik-omnivore/index.js:82:7
[Wed, 04 Nov 2015 17:07:50 GMT] [error] [8456748d-c9a1-447e-8256-da14b5e3acc0]     at Object.oncomplete (fs.js:107:15)
[Wed, 04 Nov 2015 17:07:50 GMT] [info] [8456748d-c9a1-447e-8256-da14b5e3acc0] [cigl1ze2y008yt7m3ohbd45k7] Cleaned up temporary folder
[Wed, 04 Nov 2015 17:07:50 GMT] [info] [8456748d-c9a1-447e-8256-da14b5e3acc0] [watchbot] Service exit code: 8
```

**Comment by rclark** [comment]
Could you provide a link to a file with an unrecognized projection? We'll need a fixture to test this case.

**Comment by isiyu** [comment]
this was the test case upload that was causing the issue. 
` s3://mapbox/tmp/isiyu/dimentians_unrecognizedProjection.tif`

**Comment by mapsam** [comment]
Digging into this one a bit more, I resized the tiff provided by @isiyu so it's a bit more manageable:

```
s3://mapbox/playground/mapsam/dimentians_unrecognizedProjection-small.tif
```

We get segfault when running `perform-preprocessorcery dimentians_unrecognizedProjection-small.tif`. This originates in wmtiff, so I think the issue should be handled there. https://github.com/mapbox/node-wmtiff/issues/9

**Comment by mapsam** [comment]
Just noting, that even our try/catch here https://github.com/mapbox/preprocessorcerer/blob/master/preprocessors/tif-reproject.preprocessor.js#L6-L7 isn't failing, and preprocessorcerer just hangs without failing.

**Comment by springmeyer** [comment]
> Is it worth making wmtiff asynchronous so we can catch and return errors from gdal?

Per https://github.com/mapbox/node-wmtiff/issues/9#issuecomment-305852692 I don't think making `wmtiff` async will make any difference.  The segfault needs to be fixed at the source.

`just hangs without failing` - It is possible that is a symptom of the underlying bug. Sometimes a segfault can manifest randomly as a hang in the threadpool (I see this on OS X occasionally).  So, you might run the test and 9 times out of 10 it would segfault, but the other time it will hang. Profiling in Activity Monitor on OS X will show one the the threads hung in memory allocation. An explanation for this is that a bug that causes a segfault is potentially corrupting memory. When memory is corrupted anything goes.

**Comment by GretaCB** [comment]
> When memory is corrupted anything goes.

This makes so much sense. I was locally testing scanline vs pyramid tiling for a troublesome file last week, and sometimes it would just hang/timeout, other times it would segfault. Thanks for this response @springmeyer
